name: Deploy to Render
env:
  deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}


on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Name of Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
      - name: Install dependencies
        run: npm install

      - name: Deploy to Render
        run: curl "$deploy_url"