name: Deploy

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - develop

env: 
  DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Test
        run:
          npm install
          npm run test


      - name: Deploy
        run:
          curl "$DEPLOY_URL"