# name: Deploy

# on:
#   push:
#     branches: [main]
#   pull request:
#     branches:
#       - main

# jobs:
#   ci:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4

#       - name: Test
#         run:
#           npm install
#           npm run test

#       - name: Deploy
#         if: github.ref == 'ref/heads/main'
#         env:
#           DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
#         run:
#           curl "$DEPLOY_URL"