name: Deploy to Render

on:
  push:
    branches:
      - main

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build

      - name: Run Cypress tests before deploy
        uses: cypress-io/github-action@v6
        with: 
          start: npm start  # Command to start your application


      - name: Deploy to Render
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$DEPLOY_URL" ]; then
            echo "Error: DEPLOY_URL is not set!"
            exit 1
          fi
          curl -X POST "$DEPLOY_URL"