name: Deploy to Render

on:
  push:
    branches: [main]
  pull_request:
    branches:
      - develop

jobs:
  cypress:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Tests
        run:
          npm install
          npm run test

      - name: Check DEPLOY_URL
        run: |
          if [ -z "$DEPLOY_URL" ]; then
            echo "DEPLOY_URL is not set!"
          else
            echo "DEPLOY_URL is set."
          fi
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
          
      - name: Deploy
        if: github.ref == 'refs/heads/main'
        env:
          DEPLOY_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run:
          curl "$DEPLOY_URL"