name: Develop Tests

on:
  pull_request:
    branches:
      - develop
      - AndrewsBranch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Cypress
        uses: cypress-io/github-action@v6
        with: 
          build: npm run build
          start: npm run start
          component: true
