name: Develop Tests

on:
  pull_request:
    branches:
      - develop
      - AndrewsBranch

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Start server
        run: npm run develop &
        run: npx wait-on http://localhost:3001

      - name: Run vitest tests
        run: npm run test

      - name: Develop Tests
        if: github.ref == 'refs/heads/main'
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          curl "$deploy_url"
